### ISSUE TITLE
Chamada dos métodos de somatório

### ISSUE THREAD

**Issue by mrbreakbeat** [mds2013gx/mds2013#11]
Estamos com problema para chamar o método que efetua a soma dos totais de crime por ano dentro da classe view... você pode nos ajudar com a solução disso para que possamos continuar em frente com os outros métodos??

**Comment by eliseuegewarth** [comment]
Consegui resolver a chamada dos métodos em todas as camadas da aplicação, porém o metodo 
CrimeDAO->somaTotalRoubo() esta quebrando a aplicação e retornando o erro:
Fatal error: Call to a member function FetchNextObject() on a non-object in C:\xampp\htdocs\mds2013\persistence\CrimeDAO.php on line 106.
