### ISSUE TITLE
Branch 'Interface_Nova' quebrou

### ISSUE THREAD

**Issue by mrbreakbeat** [mds2013gx/mds2013#12]
Tem como vc me ajudar a ajustar aqueles problemas que enfrentamos no inicio da construção dos métodos de consulta para a camada view?

Fatal error: Call to undefined method CrimeController::somaTotalHomicidios() in C:\xampp\htdocs\mds2013\controller\CrimeController.php on line 190

Sei que são só questão de omissão de alguma informação, mas estão acontecendo em vários trechos do código!

**Comment by eliseuegewarth** [comment]
O erro estava ocorrendo porque o metodo tem a assinatura _somaTotalHomicidios(); (com underscore no inicio) e a chamada estava sendo feita por somaTotalHomicidios() (sem underscore).
