### ISSUE TITLE
Problema no Parse

### ISSUE THREAD

**Issue by lucasglobal** [mds2013gx/mds2013#14]
O parse continua com o mesmo problema: Parse error: syntax error, unexpected '[', expecting ']' in C:\xampp\htdocs\mds2013\util\Parse.php on line 76

A funcao de serie histórica está apontando erro, quando a função que deveria estar funcionando era a de RA.

**Comment by Lcunha** [comment]
Problema resolvido através de interpretação lógica, o erro acontecia devido a erros de lógicas associativas nosvetores do pares Quadrimestral
