### ISSUE TITLE
Includes da View incorretos

### ISSUE THREAD

**Issue by mrbreakbeat** [mds2013gx/mds2013#4]
Na classe, CrimeView.php e CrimeController as funções includes estão com caminhos de URI ao invés de utilizar uma função como APP_PATH ou algo do tipo, estão utilizando caminhos físicos (URI), 
<?php
 include ('C:/xampp/htdocs/mds2013/view/header.php'); 
 include ('C:/xampp/htdocs/mds2013/view/viewController.php');
 include ('C:/xampp/htdocs/mds2013/view/navigation.php'); 
 include ('C:/xampp/htdocs/mds2013/view/footer.php');
?>

Acho que o Lucas Andrade é que tinha ficado responsável por isso... tem como vc resolver isso agora?

**Comment by lucasglobal** [comment]
Erros controlados, a constante anteriormente criada (__APP_PATH) estava dando erros quando uma biblioteca puxava dados e se deparava com ela, portanto, foi resolvido colocar a URL diretamente nos includes. Essa medida foi exclusivamente emergencial para o software funcionar, mas a constante que pega o caminho automaticamente será recolocada e enviada para o repositório assim que estiver funcionando sem causar interrupções durante o funcionamento do software.

**Comment by mrbreakbeat** [comment]
Perfeito!  mas e aquele lance do DOCUMENT_ROOT que você e o Carvalho tinham discutido não vai ser mais utilizado??

**Comment by lucasglobal** [comment]
Do document_root não, porque mesmo usando essa variável, o servidor ainda terá que ter a pasta mds2013 antes do projeto. Com a constante que estamos tentando implementar, qualquer alteração no nome da pasta pode ser feito e o software continuará funcionando sem problemas de diretório.
