### ISSUE TITLE
Correção de filtro de excessões

### ISSUE THREAD

**Issue by mrbreakbeat** [mds2013gx/mds2013#8]
Percebeu-se que o filtro para acionar as exceptions no trecho de código:

if(($resultado == null) || (empty($resultado) == true) || (count($resultado) == 0)){
            throw new ECategoriaListarTodasVazio();

```
    }
```

os parâmetros do IF estão testando como se o $resultado fosse inteiro... sendo que o retorno desta função é um OBJETO (ou Array), precisamos solucionar isso para que os testes passem a acionem as excessões.

**Comment by lucasglobal** [comment]
A condição não estava sendo acessada realmente porque o retorno da função era um OBJETO, e possui no retorno do SQL vários campos, como também o ARRAY com as informações da consulta. Foi preciso portanto utilizar uma função diferente para esse OBJETO retornado para acessar esse ARRAY. A solução foi essa:
<code>
if($resultado->RecordCount()== 0){
            throw new ECategoriaListarTodasVazio();
        }</code>

**Comment by mrbreakbeat** [comment]
Agora é só mudar isso la em todas as classes da persistencia (persistence)
